version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    env_file:
        - .env

volumes:
  postgres_data:
    driver: local
