global:
  scrape_interval: 15s 

  external_labels:
    monitor: 'kudago'

=
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: "/metrics"

    scrape_interval: 5s

    static_configs:
      - targets: [ '127.0.0.1:8099' ]