// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package events

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (InviteNotificationRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*InviteNotificationRequest) UnmarshalJSON([]byte) error        { return nil }
func (InviteNotificationRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*InviteNotificationRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_InviteNotificationRequest *InviteNotificationRequest
