// Code generated by MockGen. DO NOT EDIT.
// Source: csat.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "kudago/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCSATService is a mock of CSATService interface.
type MockCSATService struct {
	ctrl     *gomock.Controller
	recorder *MockCSATServiceMockRecorder
}

// MockCSATServiceMockRecorder is the mock recorder for MockCSATService.
type MockCSATServiceMockRecorder struct {
	mock *MockCSATService
}

// NewMockCSATService creates a new mock instance.
func NewMockCSATService(ctrl *gomock.Controller) *MockCSATService {
	mock := &MockCSATService{ctrl: ctrl}
	mock.recorder = &MockCSATServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCSATService) EXPECT() *MockCSATServiceMockRecorder {
	return m.recorder
}

// AddAnswers mocks base method.
func (m *MockCSATService) AddAnswers(ctx context.Context, answers []models.Answer, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAnswers", ctx, answers, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAnswers indicates an expected call of AddAnswers.
func (mr *MockCSATServiceMockRecorder) AddAnswers(ctx, answers, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAnswers", reflect.TypeOf((*MockCSATService)(nil).AddAnswers), ctx, answers, userID)
}

// GetStatistics mocks base method.
func (m *MockCSATService) GetStatistics(ctx context.Context) ([]models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistics", ctx)
	ret0, _ := ret[0].([]models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistics indicates an expected call of GetStatistics.
func (mr *MockCSATServiceMockRecorder) GetStatistics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistics", reflect.TypeOf((*MockCSATService)(nil).GetStatistics), ctx)
}

// GetTest mocks base method.
func (m *MockCSATService) GetTest(ctx context.Context, query string) (models.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTest", ctx, query)
	ret0, _ := ret[0].(models.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTest indicates an expected call of GetTest.
func (mr *MockCSATServiceMockRecorder) GetTest(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTest", reflect.TypeOf((*MockCSATService)(nil).GetTest), ctx, query)
}
