// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package events

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1c6ff278DecodeKudagoInternalGatewayEvent(in *jlexer.Lexer, out *InviteNotificationRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user_id":
			out.UserID = int(in.Int())
		case "event_id":
			out.EventID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1c6ff278EncodeKudagoInternalGatewayEvent(out *jwriter.Writer, in InviteNotificationRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.UserID))
	}
	{
		const prefix string = ",\"event_id\":"
		out.RawString(prefix)
		out.Int(int(in.EventID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InviteNotificationRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1c6ff278EncodeKudagoInternalGatewayEvent(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InviteNotificationRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1c6ff278EncodeKudagoInternalGatewayEvent(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InviteNotificationRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1c6ff278DecodeKudagoInternalGatewayEvent(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InviteNotificationRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1c6ff278DecodeKudagoInternalGatewayEvent(l, v)
}
